version: '3.8'
services:
  reservations:
    build: ./reservations-service
    ports:
      - "3000:3000"
    environment:
      - DB_USER=tu_usuario
      - DB_PASSWORD=tu_contraseña
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=restaurant_reservations
    depends_on:
      - db
  
  users:
    build: ./users-service
    ports:
      - "3001:3001"
    environment:
      - DB_USER=tu_usuario
      - DB_PASSWORD=tu_contraseña
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=restaurant_users
      - JWT_SECRET=tu_secreto_jwt
    depends_on:
      - db
  
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - reservations
      - users
    environment:
      - JWT_SECRET=tu_secreto_jwt

  db:
    image: postgres
    environment:
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: tu_contraseña
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
